Repository BESTSELLER/nightscaler, pull requests merged in 2023-04, with the labels that each got.

#11 CI: Testing new configurations for `release-drafter`
  .github/release-drafter-helm.yml
  .github/release-drafter.yml
Labels: CI

#12 CI: This should fix uncategorised prs
  .github/release-drafter-helm.yml
  .github/release-drafter.yml
Labels: CI

#13 Bug: Helm chart is invalid
  .github/workflows/release-chart.yml
  chart/Chart.yaml
  chart/templates/NOTES.txt
  chart/templates/deployment.yaml
  chart/templates/tests/test-connection.yaml
  chart/values.yaml
Labels: bug, helm-chart

#14 Bug: Added info messages + Corrected action string `kscale_scale_namespace_up` + Expanded config struct with `DEBUG` bool
  pkg/config/config.go
  pkg/pubsub/Listen.go
  pkg/pubsub/createSubscription.go
Labels: bug, enhancement

#15 CI: Fix so build container image only runs on application release + Pointing chart releaser to the correct folder
  .github/workflows/build_container.yml
  .github/workflows/release-chart.yml
Labels: CI

#17 bug: Fix wrongly parsed time string for scaling
  main.go
  pkg/k8s/ScaleNamespaceUp.go
  pkg/pubsub/Listen.go
  pkg/pubsub/createSubscription.go
Labels: patch

#18 bug: Log presented wrong unit
  pkg/k8s/ScaleNamespaceUp.go
  pkg/pubsub/Listen.go
Labels: patch

#20 CI: Fully functional GitHub action to release Helm chart
  .github/workflows/release-chart.yml
Labels: CI

#19 Improvement: Made the docker image smaller
  Dockerfile
Labels: improvement
