Repository BESTSELLER/nightscaler, pull requests merged in 2023-05, with the labels that each got.

#27 Feat: Google Instance Metadata to get cluster name
  pkg/config/config.go
  pkg/instancemetadata/GetGCPInstanceMetadata.go
Labels: new-feature

#29 Feat: Reuse subscription and enable scaling
  pkg/pubsub/Listen.go
  pkg/pubsub/createSubscription.go
Labels: new-feature, app

#32 Chart testing using `chart-testing-action`
  .github/dependabot.yml
  .github/workflows/lint-test.yaml
  .github/workflows/release-chart.yml
  .gitignore
  charts/kcale/.helmignore
  charts/kcale/Chart.yaml
  charts/kcale/templates/_helpers.tpl
  charts/kcale/templates/deployment.yaml
  charts/kcale/templates/hpa.yaml
  charts/kcale/templates/serviceaccount.yaml
  charts/kcale/values.yaml
  ct.yaml
  lintconf.yaml
Labels: new-feature, helm-chart

#37 bug: CI doesn't replace values in `chart.yaml` correctly
  .github/workflows/release-chart.yml
Labels: helm-chart, CI, github_actions

#38 Feat: Added timezones to config to improve time string control
  Dockerfile
  main.go
  pkg/config/config.go
  pkg/k8s/ScaleNamespaceUp.go
Labels: new-feature, minor, app

#41 Feat: Added zerolog logging for JSON logging
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/k8s/ScaleNamespaceUp.go
  pkg/logger/logger.go
  pkg/pubsub/Listen.go
  pkg/pubsub/createSubscription.go
  pkg/pubsublite/Listen.go
  pkg/pubsublite/client.go
Labels: new-feature, minor, app

#43 Bug: Correcting timezone stuff and default to UTC
  pkg/config/config.go
  pkg/k8s/ScaleNamespaceUp.go
Labels: patch, app

#44 Feat: Parsing more values to the deployment
  charts/kcale/templates/deployment.yaml
  charts/kcale/values.yaml
Labels: minor, helm-chart
